image: ubuntu:16.04

stages: 
 - build

build:
  stage: build 
  before_script: 
  - apt-get update -qq
  - apt install -y -qq git
  - git submodule update --init --recursive
  script:
  - apt-get install -y -qq autoconf automake cmake g++ git libbz2-dev libsnappy-dev libssl-dev libtool make pkg-config python3 python3-jinja2 doxygen libboost-chrono-dev libboost-context-dev libboost-coroutine-dev libboost-date-time-dev libboost-filesystem-dev libboost-iostreams-dev libboost-locale-dev libboost-program-options-dev libboost-serialization-dev libboost-signals-dev libboost-system-dev libboost-test-dev libboost-thread-dev libncurses5-dev libreadline-dev perl
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc) steemd
  - make -j$(nproc) cli_wallet


